plugins {
	id "java"
}

apply from: rootProject.file("gradle/platform.gradle")

architectury {
	platformSetupLoomIde()
	fabric()
}

configurations {
	common
	shadowCommon
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentFabric.extendsFrom common
}

dependencies {
	modImplementation "net.fabricmc:fabric-loader:0.19.3"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.116.15+1.21.1"
	modImplementation "dev.architectury:architectury-fabric:13.0.11"
	modCompileOnly files(rootProject.mtrCommonDevJar)
	modCompileOnly files(rootProject.mtrFabricDevJar)
	modLocalRuntime files(rootProject.mtrFabricReleaseJar)

	common(project(path: ":common", configuration: "namedElements")) { transitive = false }
	shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive = false }
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", rootProject.minecraftVersion
	inputs.property "mtr_min_version", rootProject.mtr_min_version

	filesMatching("fabric.mod.json") {
		expand(
			"version": project.version,
			"minecraft_version": rootProject.minecraftVersion,
			"mtr_min_version": rootProject.mtr_min_version
		)
	}
}

shadowJar {
	configurations = [project.configurations.shadowCommon]
	archiveClassifier.set("dev-shadow")
}

remapJar {
	input.set shadowJar.archiveFile
	dependsOn shadowJar
	archiveBaseName.set("JCM-fabric")
	archiveClassifier.set("")
}

components.java {
	withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
		skip()
	}
}
