plugins {
	id "java"
}

architectury {
	platformSetupLoomIde()
	neoForge()
}

apply from: rootProject.file("gradle/platform.gradle")

configurations {
	common
	shadowCommon
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentNeoForge.extendsFrom common
}

dependencies {
	neoForge "net.neoforged:neoforge:21.1.248"
	modImplementation "dev.architectury:architectury-neoforge:13.0.11"
	modCompileOnly files(rootProject.mtrCommonDevJar)
	modCompileOnly files(rootProject.mtrNeoForgeDevJar)
	modLocalRuntime files(rootProject.mtrNeoForgeReleaseJar)

	common(project(path: ":common", configuration: "namedElements")) { transitive = false }
	shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", rootProject.minecraftVersion
	inputs.property "mtr_min_version", rootProject.mtr_min_version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand(
			"version": project.version,
			"minecraft_version": rootProject.minecraftVersion,
			"mtr_min_version": rootProject.mtr_min_version
		)
	}
}

shadowJar {
	configurations = [project.configurations.shadowCommon]
	archiveClassifier.set("dev-shadow")
}

remapJar {
	input.set shadowJar.archiveFile
	dependsOn shadowJar
	archiveBaseName.set("JCM-neoforge")
	archiveClassifier.set("")
}

components.java {
	withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
		skip()
	}
}
